server:
  port: 7207

spring:
  application:
    name: ADMIN-SERVER

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    healthCheckUrl: /actuator/health
    metadata-map:
      startup: ${random.int}
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:7201/eureka/
  endpoint.health.show-details: always


management:
  tracing:
    sampling:
      probability: "1.0"