server:
  port: 7202

spring:
  application:
    name: EMPLOYEE-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7201/eureka/

management:
  tracing:
    sampling:
      probability: "1.0"