server:
  port: 7201

spring:
  application:
    name: EUREKA-SERVER
  boot:
    admin:
      client:
        url: http://localhost:7207

eureka:
  client:
    service-url:
      default-zone: http://localhost:7201/eureka/

management:
  tracing:
    sampling:
      probability: "1.0"
  endpoints:
    web:
      exposure:
        include:
          - "*"