server:
  port: 7204

spring:
  application:
    name: NOTIFICATION-SERVICE

  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: 127.0.0.1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7201/eureka/

ms:
  rabbit:
    exchange:
      name: pro-exchange
    queue:
      name: pro-queue
    routing:
      name: pro-routing