server:
  port: 7204

spring:
  application:
    name: NOTIFICATION-SERVICE

  datasource:
    username: postgres
    password: 12345
    url: jdbc:postgresql://localhost:5432/notificationDB

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: 127.0.0.1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7201/eureka/

ms:
  rabbit:
    exchange:
      name: pro-exchange
    queue:
      name: pro-queue
    routing:
      name: pro-routing

management:
  tracing:
    sampling:
      probability: "1.0"