server:
  port: 7204

spring:
  application:
    name: NOTIFICATION-SERVICE

  rabbitmq:
    username: admin
    password: s3cr3t
    port: 5672
    host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7201/eureka/